### PR TITLE
Adding MOH filtering possibility to RDHS

### PR DESCRIPTION
**Pull request by diniduhewage**

### CODE REVIEW

**Comment by buddhika75** [comment]
Please resolve conflicts and update the request.

**Comment by buddhika75** [comment]
Please resolve conflicts and create the pull request again.

**Comment by buddhika75** [comment]
Please resolve conflicts and create the pull request again. Thanks

**Comment by diniduhewage** [comment]
> Please resolve conflicts and create the pull request again. Thanks

Done, Please check again. :)

**Pull request merged**
